owner: jmccabe-harmelin
repo: ghost

# Add your sites here
sites:
  - name: Briefcase
    url: https://briefcase.harmelin.com
  - name: Harmelin Media
    url: https://harmelin.com

status-website:
  baseUrl: /ghost
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
