owner: jmccabe-harmelin # GitHub username
repo: ghost # GitHub repo name
user-agent: jmccabe-harmelin
sites:
  - name: Briefcase
    url: $BRIEFCASE_URL
    assignees:
    - jmccabe-harmelin
  - name: Harmelin Media
    url: https://harmelin.com

status-website:
  baseUrl: /ghost
  name: Upptime
  theme: dark
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *" # Every 5 minutes

# Docs https://upptime.js.org/docs/configuration
