owner: jmccabe-harmelin # GitHub username
repo: ghost # GitHub repo name
user-agent: jmccage-harmelin
sites:
  - name: Briefcase
    url: $BRIEFCASE_URL
  - name: Harmelin Media
    url: https://harmelin.com

status-website:
  baseUrl: /ghost
  name: Upptime
  theme: dark
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *" # changed from default */5 to */15

# Docs https://upptime.js.org/docs/configuration
